[config]
schemaVersion = "0.0.1"


[package]
namespace = "AswehDebrej"
name = "Limitless_Poms_Hephaestus"
versionNumber = "0.1.0"
description = "Pom of Power keeps upgrading Hephaestus boons (Volcanic Strike, Volcanic Flourish, Smithy Rush) past their vanilla cooldown limit, with diminishing returns."
websiteUrl = "https://github.com/AswehDebrej/Limitless_Poms"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.112"
LuaENVY-ENVY = "1.2.1"
SGG_Modding-ModUtil = "4.0.1"
SGG_Modding-ReLoad = "1.0.3"
SGG_Modding-Chalk = "2.1.2"
AswehDebrej-Limitless_Poms_Core = "0.1.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Uncomment (remove the #) the three lines below if you have any files to copy to the plugins_data folder (like custom .pkg files)
# [[build.copy]]
# source = "./data"
# target = "./plugins_data"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods" ]
